"""
Mock Data Seeder — Populates the database with realistic football matches
for testing the ML model and mobile app display.
"""

import datetime
import logging
from sqlalchemy import select
from app.models.database import async_session
from app.models.match import Match

logger = logging.getLogger(__name__)

# 8 realistic mock matches across top leagues
MOCK_MATCHES = [
    # ── Premier League ────────────────────────────────
    {
        "fixture_id": 100001,
        "league_name": "Premier League",
        "league_id": 39,
        "league_logo": "https://media.api-sports.io/football/leagues/39.png",
        "country": "England",
        "home_team": "Manchester City",
        "away_team": "Arsenal",
        "home_logo": "https://media.api-sports.io/football/teams/50.png",
        "away_logo": "https://media.api-sports.io/football/teams/42.png",
        "status": "2H",
        "elapsed": 67,
        "score_home": 2,
        "score_away": 1,
        "odd_home": 1.85,
        "odd_draw": 3.60,
        "odd_away": 4.20,
        "tournament_type": 0,
        "shots_home": 14,
        "shots_away": 9,
        "corners_home": 7,
        "corners_away": 4,
        "red_cards_home": 0,
        "red_cards_away": 0,
        "is_live": True,
    },
    {
        "fixture_id": 100002,
        "league_name": "Premier League",
        "league_id": 39,
        "league_logo": "https://media.api-sports.io/football/leagues/39.png",
        "country": "England",
        "home_team": "Liverpool",
        "away_team": "Chelsea",
        "home_logo": "https://media.api-sports.io/football/teams/40.png",
        "away_logo": "https://media.api-sports.io/football/teams/49.png",
        "status": "1H",
        "elapsed": 33,
        "score_home": 1,
        "score_away": 1,
        "odd_home": 1.65,
        "odd_draw": 3.80,
        "odd_away": 5.50,
        "tournament_type": 0,
        "shots_home": 8,
        "shots_away": 6,
        "corners_home": 4,
        "corners_away": 3,
        "red_cards_home": 0,
        "red_cards_away": 1,
        "is_live": True,
    },
    # ── La Liga ───────────────────────────────────────
    {
        "fixture_id": 100003,
        "league_name": "La Liga",
        "league_id": 140,
        "league_logo": "https://media.api-sports.io/football/leagues/140.png",
        "country": "Spain",
        "home_team": "Real Madrid",
        "away_team": "Barcelona",
        "home_logo": "https://media.api-sports.io/football/teams/541.png",
        "away_logo": "https://media.api-sports.io/football/teams/529.png",
        "status": "2H",
        "elapsed": 78,
        "score_home": 3,
        "score_away": 2,
        "odd_home": 2.10,
        "odd_draw": 3.40,
        "odd_away": 3.50,
        "tournament_type": 0,
        "shots_home": 18,
        "shots_away": 15,
        "corners_home": 8,
        "corners_away": 6,
        "red_cards_home": 0,
        "red_cards_away": 0,
        "is_live": True,
    },
    {
        "fixture_id": 100004,
        "league_name": "La Liga",
        "league_id": 140,
        "league_logo": "https://media.api-sports.io/football/leagues/140.png",
        "country": "Spain",
        "home_team": "Atletico Madrid",
        "away_team": "Sevilla",
        "home_logo": "https://media.api-sports.io/football/teams/530.png",
        "away_logo": "https://media.api-sports.io/football/teams/536.png",
        "status": "NS",
        "elapsed": 0,
        "score_home": 0,
        "score_away": 0,
        "odd_home": 1.70,
        "odd_draw": 3.60,
        "odd_away": 5.00,
        "tournament_type": 0,
        "shots_home": 0,
        "shots_away": 0,
        "corners_home": 0,
        "corners_away": 0,
        "red_cards_home": 0,
        "red_cards_away": 0,
        "is_live": False,
    },
    # ── Bundesliga ────────────────────────────────────
    {
        "fixture_id": 100005,
        "league_name": "Bundesliga",
        "league_id": 78,
        "league_logo": "https://media.api-sports.io/football/leagues/78.png",
        "country": "Germany",
        "home_team": "Bayern Munich",
        "away_team": "Borussia Dortmund",
        "home_logo": "https://media.api-sports.io/football/teams/157.png",
        "away_logo": "https://media.api-sports.io/football/teams/165.png",
        "status": "HT",
        "elapsed": 45,
        "score_home": 0,
        "score_away": 0,
        "odd_home": 1.50,
        "odd_draw": 4.20,
        "odd_away": 6.50,
        "tournament_type": 0,
        "shots_home": 10,
        "shots_away": 3,
        "corners_home": 6,
        "corners_away": 1,
        "red_cards_home": 0,
        "red_cards_away": 0,
        "is_live": True,
    },
    {
        "fixture_id": 100006,
        "league_name": "Bundesliga",
        "league_id": 78,
        "league_logo": "https://media.api-sports.io/football/leagues/78.png",
        "country": "Germany",
        "home_team": "RB Leipzig",
        "away_team": "Bayer Leverkusen",
        "home_logo": "https://media.api-sports.io/football/teams/173.png",
        "away_logo": "https://media.api-sports.io/football/teams/168.png",
        "status": "FT",
        "elapsed": 90,
        "score_home": 1,
        "score_away": 3,
        "odd_home": 2.80,
        "odd_draw": 3.30,
        "odd_away": 2.60,
        "tournament_type": 0,
        "shots_home": 9,
        "shots_away": 16,
        "corners_home": 3,
        "corners_away": 9,
        "red_cards_home": 1,
        "red_cards_away": 0,
        "is_live": False,
    },
    # ── Serie A ───────────────────────────────────────
    {
        "fixture_id": 100007,
        "league_name": "Serie A",
        "league_id": 135,
        "league_logo": "https://media.api-sports.io/football/leagues/135.png",
        "country": "Italy",
        "home_team": "AC Milan",
        "away_team": "Inter Milan",
        "home_logo": "https://media.api-sports.io/football/teams/489.png",
        "away_logo": "https://media.api-sports.io/football/teams/505.png",
        "status": "1H",
        "elapsed": 22,
        "score_home": 0,
        "score_away": 1,
        "odd_home": 2.90,
        "odd_draw": 3.20,
        "odd_away": 2.50,
        "tournament_type": 0,
        "shots_home": 3,
        "shots_away": 7,
        "corners_home": 2,
        "corners_away": 4,
        "red_cards_home": 0,
        "red_cards_away": 0,
        "is_live": True,
    },
    {
        "fixture_id": 100008,
        "league_name": "Serie A",
        "league_id": 135,
        "league_logo": "https://media.api-sports.io/football/leagues/135.png",
        "country": "Italy",
        "home_team": "Juventus",
        "away_team": "Napoli",
        "home_logo": "https://media.api-sports.io/football/teams/496.png",
        "away_logo": "https://media.api-sports.io/football/teams/492.png",
        "status": "NS",
        "elapsed": 0,
        "score_home": 0,
        "score_away": 0,
        "odd_home": 2.30,
        "odd_draw": 3.30,
        "odd_away": 3.10,
        "tournament_type": 0,
        "shots_home": 0,
        "shots_away": 0,
        "corners_home": 0,
        "corners_away": 0,
        "red_cards_home": 0,
        "red_cards_away": 0,
        "is_live": False,
    },
    # ── Süper Lig ─────────────────────────────────────
    {
        "fixture_id": 100009,
        "league_name": "Süper Lig",
        "league_id": 203,
        "league_logo": "https://media.api-sports.io/football/leagues/203.png",
        "country": "Turkey",
        "home_team": "Galatasaray",
        "away_team": "Fenerbahce",
        "home_logo": "https://media.api-sports.io/football/teams/645.png",
        "away_logo": "https://media.api-sports.io/football/teams/646.png",
        "status": "2H",
        "elapsed": 82,
        "score_home": 2,
        "score_away": 2,
        "odd_home": 2.40,
        "odd_draw": 3.10,
        "odd_away": 2.60,
        "tournament_type": 0,
        "shots_home": 11,
        "shots_away": 13,
        "corners_home": 5,
        "corners_away": 6,
        "red_cards_home": 0,
        "red_cards_away": 1,
        "is_live": True,
    },
    {
        "fixture_id": 100010,
        "league_name": "Süper Lig",
        "league_id": 203,
        "league_logo": "https://media.api-sports.io/football/leagues/203.png",
        "country": "Turkey",
        "home_team": "Besiktas",
        "away_team": "Trabzonspor",
        "home_logo": "https://media.api-sports.io/football/teams/549.png",
        "away_logo": "https://media.api-sports.io/football/teams/640.png",
        "status": "HT",
        "elapsed": 45,
        "score_home": 1,
        "score_away": 0,
        "odd_home": 2.10,
        "odd_draw": 3.20,
        "odd_away": 3.40,
        "tournament_type": 0,
        "shots_home": 6,
        "shots_away": 4,
        "corners_home": 3,
        "corners_away": 2,
        "red_cards_home": 0,
        "red_cards_away": 0,
        "is_live": True,
    },
    # ── Roshn Saudi League ──────────────────────────────
    {
        "fixture_id": 100011,
        "league_name": "Roshn Saudi League",
        "league_id": 307,
        "league_logo": "https://media.api-sports.io/football/leagues/307.png",
        "country": "Saudi Arabia",
        "home_team": "Al Hilal",
        "away_team": "Al Nassr",
        "home_logo": "https://media.api-sports.io/football/teams/2962.png",
        "away_logo": "https://media.api-sports.io/football/teams/2939.png",
        "status": "2H",
        "elapsed": 61,
        "score_home": 3,
        "score_away": 1,
        "odd_home": 1.95,
        "odd_draw": 3.75,
        "odd_away": 3.40,
        "tournament_type": 0,
        "shots_home": 15,
        "shots_away": 9,
        "corners_home": 7,
        "corners_away": 5,
        "red_cards_home": 0,
        "red_cards_away": 0,
        "is_live": True,
    },
    {
        "fixture_id": 100012,
        "league_name": "Roshn Saudi League",
        "league_id": 307,
        "league_logo": "https://media.api-sports.io/football/leagues/307.png",
        "country": "Saudi Arabia",
        "home_team": "Al Ittihad",
        "away_team": "Al Ahli",
        "home_logo": "https://media.api-sports.io/football/teams/2975.png",
        "away_logo": "https://media.api-sports.io/football/teams/2933.png",
        "status": "NS",
        "elapsed": 0,
        "score_home": 0,
        "score_away": 0,
        "odd_home": 2.20,
        "odd_draw": 3.40,
        "odd_away": 2.80,
        "tournament_type": 0,
        "shots_home": 0,
        "shots_away": 0,
        "corners_home": 0,
        "corners_away": 0,
        "red_cards_home": 0,
        "red_cards_away": 0,
        "is_live": False,
    },
]


async def seed_mock_data():
    """Insert mock matches into the database if empty."""
    try:
        async with async_session() as db:
            # Check if we already have matches
            result = await db.execute(select(Match).limit(1))
            if result.scalars().first():
                logger.info("📦 Database already has matches, skipping seed")
                return False

            now = datetime.datetime.utcnow()

            for m in MOCK_MATCHES:
                # Set kick-off times relative to now
                if m["status"] == "NS":
                    kick_off = now + datetime.timedelta(hours=2)
                elif m["status"] == "FT":
                    kick_off = now - datetime.timedelta(hours=2)
                else:
                    kick_off = now - datetime.timedelta(minutes=m["elapsed"])

                match = Match(
                    fixture_id=m["fixture_id"],
                    league_name=m["league_name"],
                    league_id=m["league_id"],
                    league_logo=m["league_logo"],
                    country=m["country"],
                    home_team=m["home_team"],
                    away_team=m["away_team"],
                    home_logo=m["home_logo"],
                    away_logo=m["away_logo"],
                    status=m["status"],
                    elapsed=m["elapsed"],
                    score_home=m["score_home"],
                    score_away=m["score_away"],
                    kick_off=kick_off,
                    odd_home=m["odd_home"],
                    odd_draw=m["odd_draw"],
                    odd_away=m["odd_away"],
                    tournament_type=m["tournament_type"],
                    shots_home=m["shots_home"],
                    shots_away=m["shots_away"],
                    corners_home=m["corners_home"],
                    corners_away=m["corners_away"],
                    red_cards_home=m["red_cards_home"],
                    red_cards_away=m["red_cards_away"],
                    extra_stats={
                        "home": {
                            "possession": "55%",
                            "fouls": 12,
                            "yellow_cards": 2,
                            "offsides": 4,
                            "passes_pct": "84%",
                            "expected_goals": "1.75",
                        },
                        "away": {
                            "possession": "45%",
                            "fouls": 16,
                            "yellow_cards": 3,
                            "offsides": 1,
                            "passes_pct": "76%",
                            "expected_goals": "0.85",
                        }
                    },
                    is_live=m["is_live"],
                )
                db.add(match)

            await db.commit()
            logger.info(f"🌱 Seeded {len(MOCK_MATCHES)} mock matches!")
            return True

    except Exception as e:
        logger.error(f"❌ Mock data seeding failed: {e}")
        return False
